apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_call:
    inputs:
      manifest:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  bcbs-az-claims-api:
    if: ${{ fromJSON(inputs.manifest)['bcbs-az-claims-api']['index.docker.io/cloudbeesdemo/hackers-organized'].deploy }}
    uses: cb-golden-demo-org/hackers-organized-oct/.cloudbees/workflows/deploy.yaml
    with:
      artifact-url: ${{ fromJSON(inputs.manifest)['bcbs-az-claims-api']['index.docker.io/cloudbeesdemo/hackers-organized'].url }}
      artifact-id: ${{ fromJSON(inputs.manifest)['bcbs-az-claims-api']['index.docker.io/cloudbeesdemo/hackers-organized'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  bcbs-az-member-portal:
    if: ${{ fromJSON(inputs.manifest)['bcbs-az-member-portal']['index.docker.io/cloudbeesdemo/bcbs-az-member-portal'].deploy }}
    uses: shozab-unify-examples/bcbs-az-member-portal/.cloudbees/workflows/deploy.yaml
    with:
      artifact-url: ${{ fromJSON(inputs.manifest)['bcbs-az-member-portal']['index.docker.io/cloudbeesdemo/bcbs-az-member-portal'].url }}
      artifact-id: ${{ fromJSON(inputs.manifest)['bcbs-az-member-portal']['index.docker.io/cloudbeesdemo/bcbs-az-member-portal'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
  bcbs-az-eligibility-svc:
    if: ${{ fromJSON(inputs.manifest)['bcbs-az-eligibility-svc']['index.docker.io/cloudbeesdemo/bcbs-az-eligibility-svc'].deploy }}
    uses: shozab-unify-examples/bcbs-az-eligibility-svc/.cloudbees/workflows/deploy.yaml
    with:
      artifact-url: ${{ fromJSON(inputs.manifest)['bcbs-az-eligibility-svc']['index.docker.io/cloudbeesdemo/bcbs-az-eligibility-svc'].url }}
      artifact-id: ${{ fromJSON(inputs.manifest)['bcbs-az-eligibility-svc']['index.docker.io/cloudbeesdemo/bcbs-az-eligibility-svc'].id }}
      environment: ${{ inputs.environment }}
    secrets: inherit
    vars: inherit
